# description of this workflow, can be anything you want
name: Package and release

# we need to let GitHub know _when_ we want to release.
# this is typically only when we create a new tag.
# make sure your tags are annotated!
on:
  push:
    tags:
      - '**'

# a workflow is built up as jobs, and within these jobs are steps
jobs:

  # "release" is a job, you can name it anything you want
  release:

    # we can run our steps on pretty much anything, but the "ubuntu-latest" image is a safe bet
    runs-on: ubuntu-latest

    # specify the environment variables used by the packager, matching the secrets for the project on GitHub
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}  # this secret is pre-provided for the workflow and does not
                                                 # need to be added yourself, we just reference it here.

    # "steps" holds a list of all the steps needed to package and release our AddOn
    steps:

      # we first have to clone the AddOn project, this is a required step
      - name: Clone project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # gets entire git history, needed for automatic changelogs

      # once cloned, we just run the GitHub Action
      - name: Package and release
        uses: BigWigsMods/packager@master

  github-releases-to-discord:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Github Releases To Discord
        uses: SethCohen/github-releases-to-discord@v1.16.2
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          color: "197379"
          username: "Keystone Percentage Helper"
          avatar_url: "https://raw.githubusercontent.com/ZelionGG/KeystonePercentageHelper/main/icon.png"
          content: "||@everyone||"
          footer_title: "Keystone Percentage Helper Changelog"
          footer_icon_url: "https://raw.githubusercontent.com/ZelionGG/KeystonePercentageHelper/main/icon.png"
          footer_timestamp: true